#!/usr/bin/env python3
"""timebank-report — the broker's weekly and total reports.

Reads the Known Ledgers page (a table item: Member, Site, Slug, Ledger), each
known ledger, and the Time Transaction pages on the ledgers' sites, the sites
they WATCH and the sites of the ledgers they name; counts each transaction
page once by its home site and slug; and writes, on the broker's site:

  Timebank Weekly Report <ISO week>   one per week with transactions
  Timebank Monthly Report <YYYY-MM>   one per month with transactions (0.6.0)
  Timebank Report                     every month and week, the shares, the equity model

A known ledger may be a summary ledger (PERIODS): its entries are read from its
period pages ("Alice's Ledger 2026-09"), found by title prefix in its site's
sitemap, and its OWNER line names the member: OWNER: [[About]] (the default
when the line is absent) reads the owner's name from the Site Record on the
site's About page; an older OWNER: [[About Alice]] names "Alice". Its
logged balance — given minus received over the period ledgers' written lines —
is checked against the report's net per person and printed.

Pages are reconciled in place with fedwiki-lib's Report: the script owns the
rows and the items beneath them; a human owns where the rows sit, their ticks,
and anything else on the page. The equity workbook is written beside the total
report as assets/timebank-report/equity-model.xlsx.

  tools/timebank-report.py --known http://david.localhost:4242/view/known-ledgers [--dry-run]

A broker site on another machine (the Pi5's tailnet demo) is read over https as
usual, and written into a staging copy with --out DIR (DIR/<broker domain>/pages
and assets), which is then rsynced to that machine:

  rsync -a pi5:.wiki/ledger.timebank.private.fish STAGE/
  tools/timebank-report.py --known https://ledger.timebank.private.fish/view/known-ledgers --out STAGE --review-model
  rsync -a STAGE/ledger.timebank.private.fish/ pi5:.wiki/ledger.timebank.private.fish/

The Review Model (Phase 12), with --review-model: the tool writes the workbook
assets/review-model/review-model.xlsx on the broker's site — the Actual tab from
the transactions and the weekly totals per member, the Plan tab kept as the
planning meeting left it, the Review and Equity tabs recomputed, the Approved
sheet appended once per approved week — and refreezes every model item that
reads it: the Plan rows on each Weekly Plan page, the Review rows on each
weekly report, the shares on the total report, the Review Board and a Mouse
Bank twin. It also writes the two feed pages a sheet on a public site would
IMPORTDATA: Timebank Transactions and Timebank Weekly Totals.

  --review-model                       write the workbook and refreeze
  --plan 2026-W40 Alice 3 "Seed swap"  set one Plan row, as a sheet edit would
  --workbook-only                      with --plan: write the workbook only, so the
                                       pages' badges show the edit (for the owner's Freeze)
  --approve 2026-W40 [--approver NAME] approve the week (once only): the REVIEW
                                       item on the weekly report and the
                                       Approved sheet, then refreeze
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request
import zipfile
from xml.sax.saxutils import escape as xesc

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.expanduser("~/.claude/skills/fedwiki-lib"))
import timebank_report as tr  # noqa: E402
import review_model as rm  # noqa: E402
import review_deck as rd  # noqa: E402
import fedwiki  # noqa: E402
from report import Report, row  # noqa: E402

PROV = ("Generated by tools/timebank-report.py in wiki-plugin-timebank — the broker's report tool, run by "
        "Claude Code (claude-opus-5-5) for Phase 9 of the Timebank Verification Plan.")
NEIGHBOURS_EXTRA = ["time.peoplepowered.money"]
FARM = None  # --out DIR: write the broker's pages under DIR/<domain>/ (a staging copy) instead of the farm  # Broker Role and Timebank Reporting Choices resolve through it


# --- reading ------------------------------------------------------------------

def get_json(url: str):
    """GET json. *.localhost names do not resolve through the system resolver
    (curl and browsers special-case them), so they go to 127.0.0.1 with a Host header."""
    req = urllib.request.Request(url)
    m = re.match(r"^(https?)://([^/:]+\.localhost)(:\d+)?(/.*)$", url)
    if m:
        req = urllib.request.Request(f"{m.group(1)}://127.0.0.1{m.group(3) or ''}{m.group(4)}",
                                     headers={"Host": m.group(2) + (m.group(3) or "")})
    try:
        with urllib.request.urlopen(req, timeout=10) as r:
            return json.loads(r.read().decode("utf-8"))
    except (urllib.error.URLError, TimeoutError, ValueError):
        return None


def scheme_for(site: str) -> str:
    return "http" if re.search(r":\d+$", site) or re.search(r"(^|\.)localhost$", site) or site.endswith(".local") else "https"


def page_url(site: str, slug: str) -> str:
    return f"{scheme_for(site)}://{site}/view/{slug}"


def fetch_page(site: str, slug: str):
    return get_json(f"{scheme_for(site)}://{site}/{slug}.json")


def table_rows(text: str) -> list[dict]:
    """Rows of a Table Plugin item written as a markdown table."""
    lines = [l.strip() for l in text.split("\n") if l.strip().startswith("|")]
    if len(lines) < 2:
        return []
    cells = lambda l: [c.strip() for c in re.split(r"(?<!\\)\|", l.strip().strip("|"))]  # noqa: E731
    head = cells(lines[0])
    return [dict(zip(head, cells(l))) for l in lines[2:]]


def known_ledgers(url: str) -> tuple[str, str, list[dict]]:
    m = re.match(r"^(https?)://([^/]+)/view/([a-z0-9-]+)", url)
    if not m:
        sys.exit(f"--known must be http://site/view/slug, not {url}")
    site, slug = m.group(2), m.group(3)
    page = fetch_page(site, slug)
    if not page:
        sys.exit(f"cannot read {url}")
    table = next((i for i in page["story"] if i.get("type") == "table"), None)
    if not table:
        sys.exit(f"{url} has no table item")
    members = []
    for r in table_rows(table["text"]):
        if r.get("Site") and r.get("Slug"):
            members.append({"member": r.get("Member") or r["Slug"], "site": tr.norm_site(r["Site"]), "slug": r["Slug"].strip()})
    return site, page.get("title", "Known Ledgers"), members


def period_pages(site: str, page: dict) -> list[tuple[dict, dict]]:
    """A summary ledger's period pages, read from its site: [(ref, page)]."""
    sitemap = get_json(f"{scheme_for(site)}://{site}/system/sitemap.json")
    out = []
    for ref in tr.period_pages_of(sitemap, page.get("title")):
        pg = fetch_page(site, ref["slug"])
        if pg:
            out.append((ref, pg))
    return out


def read_ledgers(members: list[dict]) -> tuple[list[dict], list[str]]:
    ledgers, sites = [], []
    add = lambda s: sites.append(tr.norm_site(s)) if s and not any(tr.same_site(s, x) for x in sites) else None  # noqa: E731
    for m in members:
        page = fetch_page(m["site"], m["slug"])
        pages = [page] if page else []
        periods = []
        if page and tr.is_summary(page):
            got = period_pages(m["site"], page)
            periods = [ref["title"] for ref, _ in got]
            pages += [pg for _, pg in got]
            ref = tr.extract_commands("\n".join(i.get("text", "") for i in page["story"] if i.get("type") == "timebank"))["owner"]
            about = None
            if ref and ref.get("slug") == tr.ABOUT_REF["slug"]:  # OWNER: [[About]] — read its Site Record
                about = fetch_page(ref["site"] if ref.get("external") else m["site"], ref["slug"])
            owner = tr.owner_name(ref, about)
            if owner:
                m["member"] = owner
        text = "\n".join(i.get("text", "") for pg in pages for i in pg.get("story", []) if i.get("type") == "timebank")
        entries = [e for pg in pages for e in tr.ledger_entries(pg, m["site"])]
        cmd = tr.extract_commands(text)
        ledgers.append({**m, "entries": entries, "reachable": bool(page), "lineup": cmd["lineup"], "watch": cmd["watch"], "text": text,
                        "periods": periods, "logged": tr.logged_balance(entries)})
        add(m["site"])
        for s in cmd["watch"]:
            add(s)
        for e in entries:
            if e["counterparty"].get("external"):
                add(e["counterparty"]["site"])
    return ledgers, sites


def gather(sites: list[str]) -> list[dict]:
    copies = []
    for site in sites:
        sitemap = get_json(f"{scheme_for(site)}://{site}/system/sitemap.json")
        for slug in tr.transaction_candidates(sitemap):
            page = fetch_page(site, slug)
            if not page:
                continue
            home = tr.home_site(page, site)
            for f in tr.page_transactions(page, site, slug):
                copies.append({"facts": f, "site": site, "home": home})
    return copies


def unpaged_lines(ledgers: list[dict]) -> list[str]:
    out = []
    for l in ledgers:
        for e in l["entries"]:
            if not e.get("txn"):
                cp = e["counterparty"]
                where = "" if cp.get("external") else " on its own site"
                out.append(f"{l['member']}: {e['label']} {'for' if e['direction'] == 'gave' else 'from'} {cp['name']}{where}, {tr.fmt_hours(e['time'])}")
    return out


# --- writing ------------------------------------------------------------------

def name_of(ref, members) -> str:
    m = tr.member_of(ref, members)
    return m["member"] if m else f"{ref.get('name')} ({ref.get('site')})"


def num(h: float) -> str:
    return f"{h:g}" if h == round(h, 2) else f"{h:.2f}"


def people_table(summary: dict, caption: str) -> dict:
    rows = [[r["member"], num(r["given"]), num(r["received"]), num(r["net"]), r["verified"], r["awaiting"]] for r in summary["rows"]]
    return fedwiki.make_table(["Member", "Given", "Received", "Net", "Verified", "Awaiting"], rows, caption=caption, layout="table")


def transactions_table(ts: list[dict], members: list[dict], caption: str) -> dict:
    rows = []
    for t in sorted(ts, key=lambda t: (t["facts"]["date"] or 0, t["facts"]["page"].get("title") or "")):
        f = t["facts"]
        title = f["page"].get("title") or f["page"]["slug"]
        link = f"[{page_url(t['home'], f['page']['slug'])} {title}]"
        date = dt.datetime.fromtimestamp(f["date"] / 1000, dt.timezone.utc).date().isoformat() if f["date"] else ""
        rows.append([link, date, name_of(f["giver"], members), name_of(f["receiver"], members), num(f["minutes"] / 60), t["state"]])
    return fedwiki.make_table(["Transaction", "Date", "Giver", "Receiver", "Hours", "State"], rows, caption=caption, layout="table")


def shares_table(summary: dict) -> dict:
    rows = [[r["member"], num(r["given"]), f"{100 * r['share']:.1f}%"] for r in summary["rows"]]
    return fedwiki.make_table(["Member", "Hours given", "Share"], rows, caption="Each member's share of all hours given", layout="table")


def svg_item(svg: str, caption: str) -> dict:
    """Inline source: the SVG plugin takes no caption in source mode, so the
    caption rides inside the drawing as its <title> (a tooltip)."""
    return {"type": "svg", "text": svg.replace(">", f"><title>{tr._esc(caption)}</title>", 1)}


def state_counts(ts) -> str:
    c = {}
    for t in ts:
        c[t["state"]] = c.get(t["state"], 0) + 1
    return ", ".join(f"{n} {s}" for s, n in sorted(c.items(), key=lambda x: ["verified", "in dialogue", "awaiting", "unknown party"].index(x[0])))


def seed_neighbours(domain: str, slug: str, sites: list[str]) -> None:
    path = fedwiki.page_path(domain, slug, FARM)
    page = fedwiki.load_page(path)
    lead = []
    for a in page.get("journal", []):
        if a.get("type") != "fork":
            break
        lead.append(a.get("site"))
    changed = False
    for s in sites:
        if s not in lead:
            fedwiki.seed_fork(page, s)
            lead.append(s)
            changed = True
    if changed:
        fedwiki.save_page(path, page)


def weekly_title(week: str) -> str:
    return f"Timebank Weekly Report {week}"


def monthly_title(month: str) -> str:
    return f"Timebank Monthly Report {month}"


def month_name(month: str) -> str:
    return dt.date(int(month[:4]), int(month[5:]), 1).strftime("%B %Y")


def write_monthly(domain, month, ts, members, broker, stamp, write):
    s = tr.summarise(ts, members)
    first, last = tr.month_bounds(month)
    title = monthly_title(month)
    weeks = sorted({tr.iso_week(t["facts"]["date"]) for t in ts})
    lead = (f"The broker's report for {month_name(month)}: {s['count']} transactions, {tr.fmt_hours(s['total'])} given, "
            f"{state_counts(ts)}. Broker: {broker}. Generated {stamp} by tools/timebank-report.py from the ledgers on "
            f"[[Known Ledgers]] and their period ledgers for {month}; see the [[Timebank Report]] for every month.")
    r = Report(domain, farm=FARM, title=title, lead=lead, see=["Timebank Report", "Known Ledgers", "Broker Role"])
    r.section("# People", "> Hours given and received, per member.")
    r.section("# Weeks", "> The weekly reports this month touches.")
    r.section("# Transactions", "> Every transaction occasion of the month, counted once by its home site.")
    pie = tr.pie_svg([(m["member"], x["given"]) for m, x in zip(members, s["rows"])], f"Hours given, {month_name(month)}")
    r.add("# People", "Known Ledgers", row("Known Ledgers", f"{len(members)} members", f"{tr.fmt_hours(s['total'])} given this month"),
          detail=[people_table(s, f"Hours per member, {month}"),
                  fedwiki.make_item(f"**Month's total:** {tr.fmt_hours(s['total'])} given and received across {s['count']} transactions — {state_counts(ts)}."),
                  svg_item(pie, f"Who gave the hours in {month_name(month)}.")])
    for week in weeks:
        wts = [t for t in ts if tr.iso_week(t["facts"]["date"]) == week]
        r.add("# Weeks", weekly_title(week), row(weekly_title(week), f"{len(wts)} transactions this month", state_counts(wts)))
    r.add("# Transactions", "Time Transaction", row("Time Transaction", f"{s['count']} occasions", state_counts(ts)),
          detail=[transactions_table(ts, members, f"Transactions, {month}")])
    r.assets("report.json", {"month": month, "generated": stamp, "summary": s,
                             "transactions": [{"home": t["home"], "slug": t["facts"]["page"]["slug"], "item": t["facts"]["page"].get("itemId"), "state": t["state"]} for t in ts]})
    ch = r.commit(write=write, created_provenance=PROV)
    return title, s, ch


def human_day(d: dt.date) -> str:
    return f"{d.strftime('%A')} {d.day} {d.strftime('%B')} {d.year}"


def write_weekly(domain, week, ts, members, broker, stamp, write, frozen=None):
    s = tr.summarise(ts, members)
    mon, sun = tr.week_bounds(week)
    title = weekly_title(week)
    lead = (f"The broker's report for ISO week {week}, {human_day(mon)} to {human_day(sun)}: {s['count']} transactions, "
            f"{tr.fmt_hours(s['total'])} given, {state_counts(ts)}. Broker: {broker}. Generated {stamp} by tools/timebank-report.py "
            f"from the ledgers on [[Known Ledgers]]; see the [[Timebank Report]] for every week.")
    r = Report(domain, farm=FARM, title=title, lead=lead, see=["Timebank Report", "Known Ledgers", "Broker Role"])
    r.section("# People", "> Hours given and received, per member.")
    r.section("# Transactions", "> Every transaction page of the week, counted once by its home site.")
    r.section("# Review", "> Tick a transaction once the meeting has seen it; notes written between the rows are kept.")
    detail = review_detail(week, frozen, domain)
    if detail:
        r.section("# Planned against actual", "> The Review tab of the Review Model, frozen; approve the week below.")
        fig = {x["member"]: x for x in frozen["figures"]["review"][week]}
        planned = sum(x["planned"] for x in fig.values())
        given = sum(x["actual"] for x in fig.values())
        approved = rm.parse_review(detail[1]["text"])["approved"]
        r.add("# Planned against actual", weekly_plan_title(week),
              row(weekly_plan_title(week), f"{tr.fmt_hours(planned)} planned", f"{tr.fmt_hours(given)} given",
                  f"approved {approved['on']}" if approved else "not approved yet"), detail=detail)
    pie = tr.pie_svg([(m["member"], x["given"]) for m, x in zip(members, s["rows"])], f"Hours given, {week}")
    r.add("# People", "Known Ledgers", row("Known Ledgers", f"{len(members)} members", f"{tr.fmt_hours(s['total'])} given this week"),
          detail=[people_table(s, f"Hours per member, {week}"),
                  fedwiki.make_item(f"**Week's total:** {tr.fmt_hours(s['total'])} given and received across {s['count']} transactions — {state_counts(ts)}."),
                  svg_item(pie, f"Who gave the hours in {week}.")])
    r.add("# Transactions", "Time Transaction", row("Time Transaction", f"{s['count']} pages", state_counts(ts)),
          detail=[transactions_table(ts, members, f"Transactions, {week}")])
    for t in sorted(ts, key=lambda t: (t["facts"]["date"] or 0, t["facts"]["page"].get("title") or "")):
        f = t["facts"]
        title_t = f["page"].get("title") or f["page"]["slug"]
        r.add("# Review", title_t, row(title_t, f"{name_of(f['giver'], members)} gave {name_of(f['receiver'], members)} {tr.fmt_hours(f['minutes'] / 60)}", t["state"]))
    r.assets("report.json", {"week": week, "generated": stamp, "summary": s,
                             "transactions": [{"home": t["home"], "slug": t["facts"]["page"]["slug"], "state": t["state"]} for t in ts]})
    ch = r.commit(write=write, created_provenance=PROV)
    return title, s, ch


def write_total(domain, weeks, all_ts, members, broker, stamp, unpaged, write, months=None, check=None):
    s = tr.summarise(all_ts, members)
    names = [m["member"] for m in members]
    months = months or {}
    per_month = []
    for month, ts in months.items():
        ms = tr.summarise(ts, members)
        per_month.append((month, [(r["member"], r["given"]) for r in ms["rows"]]))
    span = f"{month_name(list(months)[0])} to {month_name(list(months)[-1])}" if months else "no months"
    lead = (f"The broker's total report, {span}: {s['count']} transactions, {tr.fmt_hours(s['total'])} given, "
            f"{state_counts(all_ts)}. Broker: {broker}. Generated {stamp} by tools/timebank-report.py from the ledgers on [[Known Ledgers]]. "
            f"The shares below feed the equity model: wiki computes, sheet models, wiki freezes.")
    r = Report(domain, farm=FARM, title="Timebank Report", lead=lead, see=["Known Ledgers", "Broker Role", "Timebank Reporting Choices"])
    r.section("# People", "> Hours given and received over every week, and each member's share.")
    r.section("# Months", "> One monthly report per month.")
    r.section("# Weeks", "> One weekly report per ISO week.")
    r.section("# Ledgers", "> Each summary ledger's logged balance beside the report's net.")
    r.section("# Transactions", "> Every transaction occasion, counted once by its home site.")
    bars = tr.bars_svg(per_month, names, "Hours given per month")
    r.add("# People", "Known Ledgers", row("Known Ledgers", f"{len(members)} members", f"{tr.fmt_hours(s['total'])} given in all"),
          detail=[people_table(s, "Hours per member, all weeks"),
                  fedwiki.make_item(f"**Total:** {tr.fmt_hours(s['total'])} given and received across {s['count']} transactions — {state_counts(all_ts)}."),
                  svg_item(bars, "Hours given each month, stacked by member."),
                  shares_table(s)])
    for month, ts in months.items():
        ms = tr.summarise(ts, members)
        r.add("# Months", monthly_title(month), row(monthly_title(month), f"{ms['count']} transactions", f"{tr.fmt_hours(ms['total'])} given", state_counts(ts)))
    for week, ts in weeks.items():
        ws = tr.summarise(ts, members)
        r.add("# Weeks", weekly_title(week), row(weekly_title(week), f"{ws['count']} transactions", f"{tr.fmt_hours(ws['total'])} given", state_counts(ts)))
    if check:
        rows = [[c["member"], num(c["ledger"]), num(c["report"]), num(c["diff"]), c["periods"]] for c in check]
        r.add("# Ledgers", "Summary ledgers", row("Summary ledgers", f"{len(check)} members", "logged net against report net"),
              detail=[fedwiki.make_table(["Member", "Ledger net", "Report net", "Difference", "Periods"], rows,
                                         caption="Logged balance (written lines in the period ledgers) against the report's net", layout="table"),
                      fedwiki.make_item("A difference is what is not logged yet: transaction pages awaiting a line, orphans no period ledger holds, a side whose ledger is unknown — and ledger lines with no page, which the report cannot date.")])
    detail = [transactions_table(all_ts, members, "Every transaction, all weeks")]
    if unpaged:
        detail.append(fedwiki.make_item("Not counted — ledger lines with no transaction page, so no date and no week: " + "; ".join(unpaged) + "."))
    r.add("# Transactions", "Time Transaction", row("Time Transaction", f"{s['count']} pages", state_counts(all_ts)), detail=detail)
    r.assets("report.json", {"months": list(months), "weeks": list(weeks), "generated": stamp, "summary": s, "ledger_check": check or []})
    ch = r.commit(write=write, created_provenance=PROV)
    return s, ch


# --- the equity workbook ------------------------------------------------------

def _col(n: int) -> str:
    s = ""
    n += 1
    while n:
        n, rem = divmod(n - 1, 26)
        s = chr(65 + rem) + s
    return s


def _cell(ref: str, value, style: int = 0, formula: str | None = None) -> str:
    s = f' s="{style}"' if style else ""
    f = f"<f>{xesc(formula)}</f>" if formula else ""
    if isinstance(value, str) and not formula:
        return f'<c r="{ref}" t="inlineStr"{s}><is><t>{xesc(value)}</t></is></c>'
    if isinstance(value, str):
        return f'<c r="{ref}" t="str"{s}>{f}<v>{xesc(value)}</v></c>'
    return f'<c r="{ref}"{s}>{f}<v>{value!r}</v></c>'


def _sheet(rows: list[list]) -> str:
    out = ['<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
           '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>']
    for i, cells in enumerate(rows, start=1):
        out.append(f'<row r="{i}">' + "".join(_cell(f"{_col(j)}{i}", *c) if isinstance(c, tuple) else _cell(f"{_col(j)}{i}", c)
                                              for j, c in enumerate(cells) if c is not None) + "</row>")
    out.append("</sheetData></worksheet>")
    return "".join(out)


def equity_workbook(path: str, summary: dict, all_ts: list[dict], members: list[dict], multipliers: dict | None = None) -> None:
    """Shares!A1:E5 — Member, Hours given, Multiplier, Weighted hours, Share — with
    formulas AND their cached values (the Model Plugin reads cached values, never
    evaluates). Transactions sheet: the report's Transactions table, as values.
    Deterministic bytes: the same figures give the same file, so the model
    item's REVISION stays Up to date across re-runs."""
    multipliers = multipliers or {}
    rows = summary["rows"]
    n = len(rows)
    weighted = [r["given"] * multipliers.get(r["member"], 1.0) for r in rows]
    wsum = sum(weighted)
    shares = [[("Member", 1), ("Hours given", 1), ("Multiplier", 1), ("Weighted hours", 1), ("Share", 1)]]
    for i, r in enumerate(rows, start=2):
        m = multipliers.get(r["member"], 1.0)
        shares.append([r["member"], (r["given"], 2), (m, 2), (weighted[i - 2], 2, f"B{i}*C{i}"),
                       ((weighted[i - 2] / wsum) if wsum else 0, 3, f"IF(SUM(D$2:D${n + 1})=0,0,D{i}/SUM(D$2:D${n + 1}))")])
    t = n + 2
    shares.append([("Total", 1), (sum(r["given"] for r in rows), 2, f"SUM(B2:B{n + 1})"), None,
                   (wsum, 2, f"SUM(D2:D{n + 1})"), (1.0 if wsum else 0, 3, f"SUM(E2:E{n + 1})")])
    shares.append([])
    shares.append(["Hours given come from the broker's Timebank Report on david.localhost; the multiplier is the kind-of-work weight the circle agrees (1 = plain hours). This sheet cannot IMPORTDATA a localhost URL, so the report tool writes the values."])
    txs = [[("Transaction", 1), ("Date", 1), ("Giver", 1), ("Receiver", 1), ("Hours", 1), ("State", 1)]]
    for tx in sorted(all_ts, key=lambda t: (t["facts"]["date"] or 0, t["facts"]["page"].get("slug"))):
        f = tx["facts"]
        date = dt.datetime.fromtimestamp(f["date"] / 1000, dt.timezone.utc).date().isoformat() if f["date"] else ""
        txs.append([f["page"].get("title") or f["page"]["slug"], date, name_of(f["giver"], members), name_of(f["receiver"], members),
                    (f["minutes"] / 60, 2), tx["state"]])
    parts = {
        "[Content_Types].xml": '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>',
        "_rels/.rels": '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
        "xl/workbook.xml": '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Shares" sheetId="1" r:id="rId1"/><sheet name="Transactions" sheetId="2" r:id="rId2"/></sheets><definedNames><definedName name="EquityShares">Shares!$A$1:$E$' + str(n + 2) + '</definedName></definedNames></workbook>',
        "xl/_rels/workbook.xml.rels": '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
        "xl/styles.xml": '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="2"><numFmt numFmtId="164" formatCode="0.0"/><numFmt numFmtId="165" formatCode="0.0%"/></numFmts><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="4"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/><xf numFmtId="165" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs></styleSheet>',
        "xl/worksheets/sheet1.xml": _sheet(shares),
        "xl/worksheets/sheet2.xml": _sheet(txs),
    }
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as z:
        for name, data in parts.items():
            info = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            z.writestr(info, data)
    os.replace(tmp, path)


def ensure_model_item(domain: str, xlsx: str, n: int, freeze: str) -> str:
    """Place a Model Plugin item freezing Shares!A1:E(n+2) after the Shares table,
    once. Afterwards it is the owner's: its badge says Up to date or Update
    available against the workbook, and a Freeze in the browser refreshes it."""
    path = fedwiki.page_path(domain, "timebank-report", FARM)
    page = fedwiki.load_page(path)
    if any(i.get("type") == "model" for i in page["story"]):
        return "model item already on the page — left to its badge and the owner's Freeze"
    if not os.path.exists(freeze):
        return f"no model item: wiki-model-freeze not found at {freeze}"
    out = subprocess.run(["node", freeze, xlsx, "--source", "/assets/timebank-report/equity-model.xlsx", "--sheet", "Shares",
                          "--range", f"A1:E{n + 2}", "--caption", "Equity shares, frozen from the workbook", "--layout", "table"],
                         capture_output=True, text=True, check=True).stdout.strip()
    at = next((k for k, i in enumerate(page["story"]) if i.get("type") == "table" and "CAPTION Each member's share" in i.get("text", "")), None)
    at = len(page["story"]) if at is None else at + 1
    item = fedwiki.make_item(out, type="model")
    fedwiki.add_journal(page, "add", item, after=page["story"][at - 1]["id"] if at else None, provenance=PROV)
    page["story"].insert(at, item)
    fedwiki.save_page(path, page)
    return "placed the model item after the Shares table"


# --- the review model (Phase 12) ------------------------------------------------

MODEL_SRC = "/assets/review-model/review-model.xlsx"
REVIEW_PROV = ("Generated by tools/timebank-report.py --review-model in wiki-plugin-timebank — the broker's report tool, "
               "run by Claude Code (claude-opus-5-5) for Phase 12 of the Timebank Verification Plan.")
REVISION_RE = re.compile(r"^REVISION\s+sha256:([0-9a-f]+)", re.M)


def review_txs(ts: list[dict], members: list[dict]) -> list[dict]:
    out = []
    for t in ts:
        f = t["facts"]
        date = dt.datetime.fromtimestamp(f["date"] / 1000, dt.timezone.utc).date().isoformat()
        explicit = re.search(r"\bCategory:\s*([A-Za-z]+)", f.get("note") or "")
        out.append({"date": date, "week": tr.iso_week(f["date"]), "title": f["page"].get("title") or f["page"]["slug"],
                    "giver": name_of(f["giver"], members), "receiver": name_of(f["receiver"], members),
                    "hours": f["minutes"] / 60, "category": rm.category_of(f.get("label"), explicit and explicit.group(1)),
                    "state": t["state"], "url": page_url(t["home"], f["page"]["slug"])})
    return out


def freeze(freeze_js: str, xlsx: str, sheet: str, rng: str, caption: str, columns: str | None = None,
           existing: str | None = None, layout: str = "table") -> str:
    """wiki-model-freeze's text for one range; the existing text when the figures
    (the REVISION hash of the shown values) have not moved, so a rerun is a no-op."""
    cmd = ["node", freeze_js, xlsx, "--source", MODEL_SRC, "--sheet", sheet, "--range", rng, "--caption", caption, "--layout", layout]
    if columns:
        cmd += ["--columns", columns]
    text = subprocess.run(cmd, capture_output=True, text=True, check=True).stdout.strip()
    if existing:
        old, new = REVISION_RE.search(existing), REVISION_RE.search(text)
        same_range = f"RANGE {rng}" in existing and f"SHEET {sheet}" in existing
        if old and new and old.group(1) == new.group(1) and same_range:
            return existing
    return text


def caption_of(text: str) -> str | None:
    m = re.search(r"^CAPTION\s+(.*)$", text or "", re.M)
    return m.group(1).strip() if m else None


def find_item(page: dict | None, pred) -> dict | None:
    return next((i for i in (page or {}).get("story", []) if pred(i)), None)


def model_with_caption(page, caption):
    return find_item(page, lambda i: i.get("type") == "model" and caption_of(i.get("text")) == caption)


def review_item(page, week):
    return find_item(page, lambda i: i.get("type") == "timebank" and rm.parse_review(i.get("text")).get("week") == week)


def load_or_none(domain: str, slug: str):
    path = fedwiki.page_path(domain, slug, FARM)
    return fedwiki.load_page(path) if os.path.exists(path) else None


def plan_caption(week: str) -> str:
    return f"Estimates for {week}, frozen from the Plan tab of the Review Model"


def review_caption(week: str) -> str:
    return f"Planned against actual for {week}, frozen from the Review tab of the Review Model"


SHARES_CAPTION = "Equity shares, frozen from the Equity tab of the Review Model"
BOARD_REVIEW_CAPTION = "Planned against actual, every planned week"


def weekly_plan_title(week: str) -> str:
    return f"Weekly Plan {week}"


def set_item_text(page: dict, item: dict, text: str, prov: str) -> bool:
    if item.get("text") == text:
        return False
    item["text"] = text
    fedwiki.add_journal(page, "edit", item, provenance=prov)
    return True


def write_weekly_plan(domain: str, week: str, text: str, write: bool) -> str:
    """Weekly Plan <week> from the Weekly Plan Template: its story cloned, the lead
    written for the week, the model item frozen. On a rerun only the model item
    is refreshed; the meeting's notes are theirs."""
    slug = fedwiki.as_slug(weekly_plan_title(week))
    path = fedwiki.page_path(domain, slug, FARM)
    if os.path.exists(path):
        page = fedwiki.load_page(path)
        item = model_with_caption(page, plan_caption(week)) or find_item(page, lambda i: i.get("type") == "model")
        if not item:
            return "no model item (left alone)"
        changed = set_item_text(page, item, text, REVIEW_PROV)
        if changed and write:
            fedwiki.save_page(path, page)
        return "refrozen" if changed else "unchanged"
    tpl = load_or_none(domain, "weekly-plan-template")
    if not tpl:
        return "no Weekly Plan Template on the site"
    mon, sun = tr.week_bounds(week)
    story = []
    for n, it in enumerate(tpl["story"]):
        t = (it.get("text") or "").strip()
        if n and it.get("type") == "markdown" and t.startswith("*") and t.endswith("*") and "\n" not in t:
            continue  # the template's placeholder guidance; the tool writes the real thing
        it = {k: v for k, v in it.items() if k != "id"}
        it["id"] = fedwiki.nid()
        story.append(it)
    story[0]["text"] = (f"The plan for ISO week {week}, {human_day(mon)} to {human_day(sun)}: each member's estimated hours and "
                        f"tasks, as the [[Planning Meeting]] wrote them in the Plan tab of the [[Review Model]]. The table is "
                        f"frozen from the workbook; its badge says whether the sheet has moved on. The week's report, "
                        f"[[{weekly_title(week)}]], sets these estimates against what was given.")
    item = find_item({"story": story}, lambda i: i.get("type") == "model")
    item["text"] = text
    page = fedwiki.make_page(weekly_plan_title(week), story, provenance=REVIEW_PROV + " Made from the [[Weekly Plan Template]].")
    if write:
        fedwiki.save_page(path, page)
        seed_neighbours(domain, slug, NEIGHBOURS_EXTRA)
    return "created from the template"


def feed_page(domain: str, title: str, lead: str, table: dict, write: bool) -> str:
    """A page whose FIRST table is the feed: /plugin/table/<slug>.csv serves it."""
    slug = fedwiki.as_slug(title)
    path = fedwiki.page_path(domain, slug, FARM)
    page = load_or_none(domain, slug)
    if page:
        item = find_item(page, lambda i: i.get("type") == "table")
        changed = set_item_text(page, item, table["text"], REVIEW_PROV)
        if changed and write:
            fedwiki.save_page(path, page)
        return "~ table" if changed else "unchanged"
    page = fedwiki.make_page(title, [lead, table, "# See\n\n- [[Review Model]] — the workbook that imports this table\n- [[Timebank Report]] — the broker's total report\n- [[Known Ledgers]] — whose transactions these are"],
                             provenance=REVIEW_PROV)
    if write:
        fedwiki.save_page(path, page)
        seed_neighbours(domain, slug, NEIGHBOURS_EXTRA)
    return "created"


def refresh_model(domain: str, slug: str, caption: str, text: str, write: bool) -> str:
    page = load_or_none(domain, slug)
    if not page:
        return "no page"
    item = model_with_caption(page, caption)
    if not item:
        return "no model item with that caption"
    changed = set_item_text(page, item, text, REVIEW_PROV)
    if changed and write:
        fedwiki.save_page(fedwiki.page_path(domain, slug, FARM), page)
    return "refrozen" if changed else "unchanged"


def shares_on_total(domain: str, text: str, write: bool) -> str:
    """The total report's model item reads the Review Model's shares, replacing
    Phase 9's equity-model.xlsx; the item keeps its place on the page."""
    path = fedwiki.page_path(domain, "timebank-report", FARM)
    page = fedwiki.load_page(path)
    item = model_with_caption(page, SHARES_CAPTION) or find_item(page, lambda i: i.get("type") == "model")
    if not item:
        at = next((k for k, i in enumerate(page["story"]) if i.get("type") == "table" and "CAPTION Each member's share" in i.get("text", "")), len(page["story"]) - 1)
        item = fedwiki.make_item(text, type="model")
        fedwiki.add_journal(page, "add", item, after=page["story"][at]["id"], provenance=REVIEW_PROV)
        page["story"].insert(at + 1, item)
        if write:
            fedwiki.save_page(path, page)
        return "placed the shares model item"
    changed = set_item_text(page, item, text, REVIEW_PROV)
    if changed and write:
        fedwiki.save_page(path, page)
    return "refrozen the shares model item" if changed else "shares model item unchanged"


def review_model_step(a, domain: str, broker_site: str, members: list[dict], ts: list[dict]) -> dict:
    """Write the workbook; return the frozen texts the pages need."""
    root, _ = fedwiki.resolve_root(domain, FARM)
    xlsx = os.path.join(str(root), "assets", "review-model", "review-model.xlsx")
    names = [m["member"] for m in members]
    info = [{"member": m["member"], "site": m["site"], "url": page_url(m["site"], m["slug"])} for m in members]
    state = rm.alias_state(rm.load_state(xlsx), names)
    for week, rows in rm.DEFAULT_PLAN.items():
        if week not in state["plan"]:
            state["plan"][week] = {rm.member_alias(k, names): v for k, v in rows.items() if rm.member_alias(k, names) in names}
    for week, member, hours, tasks in a.plan or []:
        member = rm.member_alias(member, names)
        state["plan"].setdefault(week.upper(), {})[member] = (float(hours), tasks)
        print(f"  plan {week} {member}: {hours} hours — {tasks}")
    txs = review_txs(ts, members)
    totals = rm.weekly_totals(txs, names)
    done = {x["week"] for x in state["approved"]}
    approvals = {}
    # approvals made on the report pages (the REVIEW item's Approve button) that the workbook has not burned yet
    for week in sorted(state["plan"]):
        page = load_or_none(domain, fedwiki.as_slug(weekly_title(week)))
        it = review_item(page, week)
        r = rm.parse_review(it["text"]) if it else None
        if r and r["approved"]:
            approvals[week] = it["text"]
            if week not in done:
                hours = [(rm.member_alias(m, names), h) for m, h in r["hours"]]
                state["approved"] += rm.approve_rows(week, r["approved"]["on"], r["approved"]["by"], hours, totals)
                done.add(week)
                print(f"  burned {week}: approved on the report page on {r['approved']['on']} by {r['approved']['by']}")
    if a.approve:
        week = a.approve.upper()
        if week not in state["plan"]:
            sys.exit(f"--approve {week}: no plan for {week} in the Review Model, so nothing to review")
        if week in done:
            first = next(x for x in state["approved"] if x["week"] == week)
            sys.exit(f"--approve {week}: already approved on {first['on']} by {first['approver']} — a week is burned once only")
        on = a.approved_on or dt.date.today().isoformat()
        hours = [(m, totals.get((week, m), {}).get("given", 0.0)) for m in names]
        state["approved"] += rm.approve_rows(week, on, a.approver or a.broker, hours, totals)
        approvals[week] = rm.approval_text(week, on, a.approver or a.broker, hours)
        print(f"  approved {week} on {on} by {a.approver or a.broker}: " + ", ".join(f"{m} {h:g}h" for m, h in hours))
    sheets, dnames, layout, figures = rm.build(info, txs, state)
    if not a.dry_run:
        rm.write_xlsx(xlsx, sheets, dnames)
        print(f"  wrote {xlsx}: tabs {', '.join(n for n, _ in sheets)}; shares {layout['shares']}; weeks {', '.join(layout['weeks'])}")
    else:
        print(f"  would write {xlsx}")
    tmp = xlsx if not a.dry_run else None
    frozen = {"plan": {}, "review": {}, "approvals": approvals, "figures": figures, "layout": layout, "xlsx": xlsx, "txs": txs, "totals": totals}
    if tmp:
        for week in layout["weeks"]:
            plan_page = load_or_none(domain, fedwiki.as_slug(weekly_plan_title(week)))
            ex = model_with_caption(plan_page, plan_caption(week))
            frozen["plan"][week] = freeze(a.freeze, xlsx, "Plan", layout["plan"][week], plan_caption(week),
                                          "Member, Estimated hours, Tasks", ex and ex["text"])
            rep = load_or_none(domain, fedwiki.as_slug(weekly_title(week)))
            ex = model_with_caption(rep, review_caption(week))
            frozen["review"][week] = freeze(a.freeze, xlsx, "Review", layout["review"][week], review_caption(week),
                                            "Member, Planned, Actual, Variance, Approved, Approved on, Approver", ex and ex["text"])
        total = load_or_none(domain, "timebank-report")
        ex = model_with_caption(total, SHARES_CAPTION)
        frozen["shares"] = freeze(a.freeze, xlsx, "Equity", layout["shares"], SHARES_CAPTION, existing=ex and ex["text"])
        board = load_or_none(domain, "review-board")
        ex = model_with_caption(board, BOARD_REVIEW_CAPTION)
        frozen["review_all"] = freeze(a.freeze, xlsx, "Review", layout["review_all"], BOARD_REVIEW_CAPTION, existing=ex and ex["text"])
    return frozen


def review_detail(week: str, frozen: dict, domain: str) -> list[dict] | None:
    """The weekly report's Planned against actual detail: the Review rows frozen,
    and the REVIEW item — its approval, once made, is kept word for word."""
    if not frozen or week not in frozen["review"]:
        return None
    page = load_or_none(domain, fedwiki.as_slug(weekly_title(week)))
    it = review_item(page, week)
    text = frozen["approvals"].get(week) or (it and rm.parse_review(it["text"])["approved"] and it["text"]) or \
        f"REVIEW: {week}\nApprove the week once the meeting agrees: the hours given become the approved hours, burned into the Review Model's Approved sheet once."
    return [fedwiki.make_item(frozen["review"][week], type="model"), fedwiki.make_item(text, type="timebank", unwrap=False)]


def write_review_pages(domain: str, frozen: dict, write: bool) -> None:
    for week in frozen["layout"]["weeks"]:
        print(f"  Weekly Plan {week}: {write_weekly_plan(domain, week, frozen['plan'][week], write)}")
    txs = frozen["txs"]
    rows = [[t["date"], t["week"], f"[{t['url']} {t['title']}]", t["giver"], t["receiver"], num(t["hours"]), t["category"], t["state"]] for t in
            sorted(txs, key=lambda t: (t["date"], t["title"]))]
    table = fedwiki.make_table(["Date", "Week", "Transaction", "Giver", "Receiver", "Hours", "Category", "State"], rows,
                               caption="Every transaction the broker knows of — the Review Model's Actual tab imports this", layout="table")
    print("  Timebank Transactions: " + feed_page(domain, "Timebank Transactions",
          "Every transaction the broker's tool counted, one row per occasion, with the kind of work. It is the first table on the page on purpose: the Table Plugin serves it as CSV at /plugin/table/timebank-transactions.csv, which a link-shared sheet on a public site reads with IMPORTDATA. On a private site — the laptop farm, or the tailnet — the report tool writes the [[Review Model]]'s Actual tab directly instead.",
          table, write))
    names = sorted({m for (_, m) in frozen["totals"]})
    weeks = sorted({w for (w, _) in frozen["totals"]})
    trows = []
    for w in weeks:
        for m in names:
            t = frozen["totals"].get((w, m))
            if t:
                trows.append([w, m, num(t["given"]), num(t["received"]), num(round(t["weighted"], 2))])
    table = fedwiki.make_table(["Week", "Member", "Given", "Received", "Weighted given"], trows,
                               caption="Hours per member per ISO week — the Review Model's weekly totals", layout="table")
    print("  Timebank Weekly Totals: " + feed_page(domain, "Timebank Weekly Totals",
          "Hours given and received per member per ISO week, and the hours given weighted by the kind of work. Served as CSV at /plugin/table/timebank-weekly-totals.csv for a sheet's IMPORTDATA; on a private site — the laptop farm, or the tailnet — the report tool writes the [[Review Model]]'s Actual tab directly.",
          table, write))
    print("  Timebank Report: " + shares_on_total(domain, frozen["shares"], write))
    print("  Review Board: " + refresh_model(domain, "review-board", BOARD_REVIEW_CAPTION, frozen["review_all"], write)
          + "; shares " + refresh_model(domain, "review-board", SHARES_CAPTION, frozen["shares"], write))
    print("  Mouse Bank twin: " + refresh_model(domain, "mouse-bank", SHARES_CAPTION, frozen["shares"], write))


# --- the Review Deck (0.9.0) ----------------------------------------------------

DECK_PROV = ("Generated by tools/timebank-report.py --deck in wiki-plugin-timebank — the broker's report tool, run by "
             "Claude Code (claude-opus-5-5) for Phase 1 of the Review Meeting Plan.")


def ledger_on_board(domain: str, week: str, rows: list[dict], write: bool) -> str:
    """The Review Board's Ledger check table for one week, beside its model items:
    the board's last slide reads it."""
    path = fedwiki.page_path(domain, "review-board", FARM)
    page = load_or_none(domain, "review-board")
    if not page:
        return "no Review Board"
    table = fedwiki.make_table(["Member", "Given", "Received", "Net", "Awaiting"], rd.ledger_table_rows(rows),
                               caption=rd.ledger_caption(week), layout="table")
    item = find_item(page, lambda i: i.get("type") == "table" and (caption_of(i.get("text")) or "").startswith("Ledger check"))
    if item:
        changed = set_item_text(page, item, table["text"], DECK_PROV)
        if changed and write:
            fedwiki.save_page(path, page)
        return "ledger check refreshed" if changed else "ledger check unchanged"
    models = [k for k, i in enumerate(page["story"]) if i.get("type") == "model"]
    at = models[-1] if models else len(page["story"]) - 1
    fedwiki.add_journal(page, "add", table, after=page["story"][at]["id"], provenance=DECK_PROV)
    page["story"].insert(at + 1, table)
    if write:
        fedwiki.save_page(path, page)
    return "ledger check placed"


def ensure_theme(domain: str, write: bool) -> str:
    """Review Deck Theme: written once; after that the page is the site's to restyle."""
    slug = fedwiki.as_slug(rd.THEME_TITLE)
    if load_or_none(domain, slug):
        return "kept"
    page = fedwiki.make_page(rd.THEME_TITLE, [
        "The **Review Deck Theme** dresses every [[Review Deck]] the broker's report tool writes: white slides, the board's deep blue for headings, the board's palette for links. [[Wiki Deck]] reads the directives below when it compiles a deck; change them here and the next build follows.",
        fedwiki.make_item(rd.THEME_DIRECTIVES, type="code"),
        "The slides are drawn whole — each is one svg item in a 1280 by 720 frame with its own title band and footer — so the theme sets only the frame around them, the speaker notes and any compiled slide added by hand. There is no FOOTER line on purpose: every slide already draws its own footer, and a theme footer would sit on top of it. A LOGO or CSS line must be an https address.",
        "# See\n\n- [[Review Board]] — the same slides, drawn in the page\n- [[Review Meeting Plan]] — why the board became a deck\n- [[Wiki Deck]] — the compiler that reads this theme",
    ], provenance=DECK_PROV)
    if write:
        fedwiki.save_page(fedwiki.page_path(domain, slug, FARM), page)
        seed_neighbours(domain, slug, NEIGHBOURS_EXTRA)
    return "created"


def write_slide_page(domain: str, title: str, sl: dict, deck: str, write: bool) -> str:
    slug = fedwiki.as_slug(title)
    path = fedwiki.page_path(domain, slug, FARM)
    page = load_or_none(domain, slug)
    if page:
        changed = False
        svg = find_item(page, lambda i: i.get("type") == "svg")
        if svg:
            changed |= set_item_text(page, svg, sl["svg"], DECK_PROV)
        story = page["story"]
        at = next((k for k, i in enumerate(story) if (fedwiki.heading_of(i) or "").lower() == "notes"), None)
        if at is not None and at + 1 < len(story) and story[at + 1].get("type") == "markdown":
            changed |= set_item_text(page, story[at + 1], sl["notes"], DECK_PROV)
        if changed and write:
            fedwiki.save_page(path, page)
        return "redrawn" if changed else "unchanged"
    page = fedwiki.make_page(title, [
        {"type": "svg", "text": sl["svg"]},
        "# Notes\n> Speaker notes: the figures on the slide, as prose.",
        sl["notes"],
        f"# See\n> The deck this slide belongs to.",
        f"- [[{deck}]] — the week's deck, which presents this slide\n- [[Review Board]] — the same slide, drawn in the page",
    ], provenance=DECK_PROV)
    if write:
        fedwiki.save_page(path, page)
    return "created"


def write_manifest(domain: str, week: str, text: str, masked: bool, write: bool) -> str:
    title = rd.deck_title(week)
    slug = fedwiki.as_slug(title)
    path = fedwiki.page_path(domain, slug, FARM)
    page = load_or_none(domain, slug)
    if page:
        item = find_item(page, lambda i: i.get("type") in ("code", "markdown") and re.match(r"^DECK\b", i.get("text") or ""))
        if not item:
            return "no DECK item (left alone)"
        changed = set_item_text(page, item, text, DECK_PROV)
        if changed and write:
            fedwiki.save_page(path, page)
        return "manifest updated" if changed else "manifest unchanged"
    mon, sun = tr.week_bounds(week)
    lead = (f"The **Review Deck** for ISO week {week}, {human_day(mon)} to {human_day(sun)}: the [[Review Board]]'s slides, one wiki page each, compiled by [[Wiki Deck]] into a deck the stage below presents. "
            + ("Press ⤢ Present for full screen, or add ?print-pdf to the deck's address for a PDF." if masked else
               "Press ⤢ Present for full screen. The broker signs in as presenter and everyone else who opens this page follows the slides over the [[Live Deck]] relay; add ?follow=0 to browse on your own, or ?print-pdf to the deck's address for a PDF."))
    page = fedwiki.make_page(title, [
        lead,
        fedwiki.make_item(text, type="code"),
        "The code item above is the Deck Manifest: DECK names the deck, THEME the [[Review Deck Theme]], TITLE HIDE keeps the page titles off slides that draw their own, WIDTH and HEIGHT fix the 1280 by 720 frame, LIVE the relay and PRESENTERS the logins that may drive it besides the site's owner. Each SLIDE line is one page. The report tool rewrites them when it redraws the week; `wiki-deck install` recompiles the deck into this page's assets.",
        "# See\n\n- [[Review Board]] — the board these slides come from\n- [[Weekly Review]] — the meeting the deck is for\n- [[Review Meeting Plan]] — why the board became a deck",
    ], provenance=DECK_PROV)
    if write:
        fedwiki.save_page(path, page)
        seed_neighbours(domain, slug, NEIGHBOURS_EXTRA)
    return "created"


def write_deck(a, domain: str, broker_site: str, members: list[dict], weeks: dict, stamp: str, write: bool) -> None:
    week = a.deck.upper()
    masks = rd.load_masks(a.masks) if a.masks is not None else None
    board = load_or_none(domain, "review-board")
    models = [i["text"] for i in (board or {}).get("story", []) if i.get("type") == "model"]
    ledger = {"week": week, "rows": rd.ledger_rows(tr.summarise(weeks.get(week, []), members))}
    root, _ = fedwiki.resolve_root(domain, FARM)
    slugs = sorted(os.listdir(os.path.join(str(root), "pages"))) if os.path.isdir(os.path.join(str(root), "pages")) else []
    prev = rd.previous_meeting(slugs, week)
    lines = rd.meeting_lines(load_or_none(domain, prev)) if prev else {"attendance": [], "mood": []}
    meta = {"week": week, "site": None if masks else broker_site, "broker": a.broker, "generated": dt.date.today().strftime("%-d %B %Y"),
            "page": rd.deck_title(week), "attendance": lines["attendance"], "mood": lines["mood"], "masks": masks}
    slides = rd.render(models, ledger, meta)
    titles = [rd.slide_title(week, n, sl["key"]) for n, sl in enumerate(slides, 1)]
    print(f"  Review Deck {week}: {len(slides)} slides" + (f"; attendance and mood from {prev}" if prev else "; no earlier Review Meeting page") +
          ("; names masked" if masks else ""))
    for t, sl in zip(titles, slides):
        print(f"    {t}: {write_slide_page(domain, t, sl, rd.deck_title(week), write)}")
    text = rd.manifest_text(week, titles, presenters=None if masks else (a.presenters or None), relay=None if masks else rd.RELAY)
    print(f"    {rd.deck_title(week)}: {write_manifest(domain, week, text, bool(masks), write)}")
    print(f"    {rd.THEME_TITLE}: {ensure_theme(domain, write)}")
    print(f"    compile: node ~/Code/wiki-deck/bin/wiki-deck.js install {'http' if domain.endswith('localhost') else 'https'}://{domain}/{fedwiki.as_slug(rd.deck_title(week))}.json"
          + (f" --farm {FARM}" if FARM else ""))


# --- main ---------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--known", default="http://david.localhost:4242/view/known-ledgers", help="the Known Ledgers page")
    ap.add_argument("--broker", default="David Bovill")
    ap.add_argument("--dry-run", action="store_true", help="compute and print; write nothing")
    ap.add_argument("--json", action="store_true", help="print the computed figures as JSON")
    ap.add_argument("--freeze", default=os.path.join(HERE, "..", "..", "wiki-plugin-model", "scripts", "freeze.js"),
                    help="wiki-model-freeze (wiki-plugin-model scripts/freeze.js)")
    ap.add_argument("--review-model", action="store_true", help="write the Review Model workbook and refreeze the pages that read it")
    ap.add_argument("--plan", nargs=4, action="append", metavar=("WEEK", "MEMBER", "HOURS", "TASKS"),
                    help="set one Plan row of the Review Model (implies --review-model)")
    ap.add_argument("--approve", metavar="WEEK", help="approve one week, once only (implies --review-model)")
    ap.add_argument("--approver", help="who approved (default: --broker)")
    ap.add_argument("--workbook-only", action="store_true",
                    help="write the workbook and stop: no page is written or refrozen (a sheet edit the badges should notice)")
    ap.add_argument("--approved-on", help="the approval date, YYYY-MM-DD (default: today)")
    ap.add_argument("--out", metavar="DIR",
                    help="write the broker's pages and assets under DIR/<broker domain>/ instead of the farm — for a broker site on "
                         "another machine (the Pi5's tailnet sites): rsync it from there first, run, rsync it back")
    ap.add_argument("--deck", metavar="WEEK",
                    help="write the Review Deck for WEEK: one page per slide, the manifest, the theme (implies --review-model)")
    ap.add_argument("--masks", nargs="?", const="default", metavar="MAP",
                    help="with --deck: draw the fish masks instead of names, for public output — a JSON file "
                         f"(default {rd.MASKS_FILE}) or Name=Fish,…; drops LIVE, PRESENTERS and the site name")
    ap.add_argument("--presenters", nargs="*", default=["david"],
                    help="relay logins for the manifest's PRESENTERS line (Keycloak usernames; the site owner presents anyway)")
    a = ap.parse_args()
    global FARM
    FARM = os.path.abspath(os.path.expanduser(a.out)) if a.out else None
    a.review_model = a.review_model or bool(a.plan) or bool(a.approve) or bool(a.deck)

    broker_site, _, members = known_ledgers(a.known)
    domain = re.sub(r":\d+$", "", broker_site)
    ledgers, sites = read_ledgers(members)
    copies = gather(sites)
    ts = [t for t in tr.dedupe(copies) if t["facts"]["valid"] and
          (tr.member_of(t["facts"]["giver"], members) or tr.member_of(t["facts"]["receiver"], members))]
    for t in ts:
        t["state"] = tr.state_of(t, ledgers)
    weeks = tr.by_week(ts)
    months = tr.by_month(ts)
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%-d %B %Y at %H:%M UTC")
    unpaged = unpaged_lines(ledgers)

    print(f"members {[m['member'] for m in members]}; sites read {sites}; {len(copies)} copies -> {len(ts)} transactions")
    for l in ledgers:
        print(f"  {l['member']}: {'reachable' if l['reachable'] else 'UNREACHABLE'}, {len(l['entries'])} linked entries in "
              f"{len(l['periods']) or 1} {'period ledgers' if l['periods'] else 'ledger'}, watch {l['watch']}")
    for month, mts in months.items():
        s = tr.summarise(mts, members)
        print(f"  {month}: {s['count']} transactions, {tr.fmt_hours(s['total'])} given — " +
              ", ".join(f"{r['member']} +{tr.fmt_hours(r['given'])}/-{tr.fmt_hours(r['received'])}" for r in s["rows"]) + f" — {state_counts(mts)}")
    for week, wts in weeks.items():
        s = tr.summarise(wts, members)
        print(f"  {week}: {s['count']} transactions, {tr.fmt_hours(s['total'])} given — " +
              ", ".join(f"{r['member']} +{tr.fmt_hours(r['given'])}/-{tr.fmt_hours(r['received'])}" for r in s["rows"]) + f" — {state_counts(wts)}")
    if a.json:
        print(json.dumps({"months": {m: tr.summarise(x, members) for m, x in months.items()},
                          "weeks": {w: tr.summarise(x, members) for w, x in weeks.items()}, "total": tr.summarise(ts, members),
                          "transactions": [{"home": t["home"], "slug": t["facts"]["page"]["slug"], "state": t["state"], "forks": t["forks"]} for t in ts]}, indent=1))
    check = tr.ledger_check(ledgers, tr.summarise(ts, members))
    print("  ledger check — summary ledger net (logged) against report net:")
    for c in check:
        print(f"    {c['member']}: ledger {num(c['ledger'])}h, report {num(c['report'])}h, difference {num(c['diff'])}h over {c['periods']} period ledgers")
    write = not a.dry_run
    frozen = review_model_step(a, domain, broker_site, members, ts) if a.review_model else None
    if a.workbook_only:
        print("  --workbook-only: no page written; the model items' badges will read Update available where their figures moved")
        return
    for month, mts in months.items():
        title, _, ch = write_monthly(domain, month, mts, members, a.broker, stamp, write)
        print(f"  {'wrote' if write else 'would write'} http://{broker_site}/view/{fedwiki.as_slug(title)}: {', '.join(ch) or 'unchanged'}")
        if write:
            seed_neighbours(domain, fedwiki.as_slug(title), [m["site"] for m in members if not tr.same_site(m["site"], broker_site)] + NEIGHBOURS_EXTRA)
    for week, wts in weeks.items():
        title, _, ch = write_weekly(domain, week, wts, members, a.broker, stamp, write, frozen)
        print(f"  {'wrote' if write else 'would write'} http://{broker_site}/view/{fedwiki.as_slug(title)}: {', '.join(ch) or 'unchanged'}")
        if write:
            seed_neighbours(domain, fedwiki.as_slug(title), [m["site"] for m in members if not tr.same_site(m["site"], broker_site)] + NEIGHBOURS_EXTRA)
    total, ch = write_total(domain, weeks, ts, members, a.broker, stamp, unpaged, write, months=months, check=check)
    print(f"  {'wrote' if write else 'would write'} http://{broker_site}/view/timebank-report: {', '.join(ch) or 'unchanged'}")
    if write:
        seed_neighbours(domain, "timebank-report", [m["site"] for m in members if not tr.same_site(m["site"], broker_site)] + NEIGHBOURS_EXTRA)
        if frozen:
            write_review_pages(domain, frozen, write)
            lw = (a.deck or frozen["layout"]["weeks"][-1]).upper() if (a.deck or frozen["layout"]["weeks"]) else None
            if lw:
                print("  Review Board: " + ledger_on_board(domain, lw, rd.ledger_rows(tr.summarise(weeks.get(lw, []), members)), write))

        else:
            root, _ = fedwiki.resolve_root(domain, FARM)
            xlsx = os.path.join(str(root), "assets", "timebank-report", "equity-model.xlsx")
            equity_workbook(xlsx, total, ts, members)
            print(f"  wrote {xlsx}")
            print("  " + ensure_model_item(domain, xlsx, len(members), a.freeze))
    if a.deck:
        write_deck(a, domain, broker_site, members, weeks, stamp, write)


if __name__ == "__main__":
    main()
